---
title: Filter
jupyter:
  jupytext:
    text_representation:
      extension: .qmd
      format_name: quarto
      format_version: '1.0'
      jupytext_version: 1.14.4
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---

```{=html}
<iframe class="slide-deck" src="../slides/01b-slides.html"></iframe>
```

Click [here](../slides/01b-slides.qmd) to open the slides full screen.

```{python}
from setup import *
from setup import ___, _
```


### Exercise 1: 

The code below is filtering to keep only hits where `country` is United States.
Change the filter to get hits from Canada.

```{python}
(music_top200
  >> filter(_.country == "United States")
)
```

```{python}
#| jupyter: {source_hidden: true}
#| tags: [solution-code]
(music_top200
  >> filter(_.country == "Canada")
)
```

Comparing results, which artist is in the top 3 in both (the) United States and Canada?

<details><summary>Roddy Ricch</summary>Nailed it!</details>
<details><summary>The Weeknd</summary>That artist is only top 3 in the United States</details>
<details><summary>Tones and I</summary>That artist is only top 3 in the Canada</details>


### Exercise 2: 

* Filter to keep tracks where position equals 5.

```{python}
(music_top200
  >> filter(___)
)
```

```{python}
#| jupyter: {source_hidden: true}
#| tags: [solution-code]
(music_top200
  >> filter(_.position == 5)
)
```

Which artist is in position 5 in South Africa?

<details><summary>Bad Bunny</summary>Incorrect</details>
<details><summary>Eminem</summary>That's right!</details>
<details><summary>BTS</summary>Incorrect</details>
<details><summary>Selena Gomes</summary>Incorrect</details>


### Exercise 3:

Find the top 5 songs in the `country` Hong Kong.

In the slides we discussed the `==` operator. Here is a longer list of some options!

| operator | meaning |
| -------- | ------- |
| `==`     | is equal to |
| `<`      | is less than |
| `>`      | is greater than |

```{python}
(music_top200
  >> filter(___, ___)
)
```

```{python}
#| jupyter: {source_hidden: true}
#| tags: [solution-code]
(music_top200
  >> filter(_.country == "Hong Kong", _.position < 6)
)
```

### Exercise 4: looking at The Weeknd's streams

How many times has the artist The Weeknd had over 1,000,000 streams?

<details>
    <summary>Hint:</summary>
    Do in steps. Run first to get all rows where the artist is The Weeknd, and then modify your code to get where he has over 1,000,000 streams.
</details>

```{python}
(

)
```

```{python}
#| jupyter: {source_hidden: true}
#| tags: [solution-code]
(music_top200
  >> filter(_.artist == "The Weeknd", _.streams > 1000000)
)
```
